# Generated by Django 4.1.3 on 2022-12-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IchthusWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_type', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IchthusWebApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='UserTickieAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('tickie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IchthusWebApp.tickie')),
                ('userevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IchthusWebApp.userevent')),
            ],
        ),
    ]
