# Generated by Django 4.1.3 on 2022-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IchthusWebApp', '0002_tickie_usertickieanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickie',
            name='image',
            field=models.CharField(max_length=10000000),
        ),
    ]
