# Generated by Django 4.1.3 on 2022-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IchthusWebApp', '0003_alter_tickie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickie',
            name='url',
            field=models.CharField(default='hello', max_length=1000),
            preserve_default=False,
        ),
    ]
