# Generated by Django 4.1.3 on 2022-12-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IchthusWebApp', '0004_tickie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertickieanswer',
            name='answer',
        ),
    ]
