# Generated by Django 4.1.3 on 2022-12-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IchthusWebApp', '0005_remove_usertickieanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
