# Generated by Django 4.1.3 on 2022-12-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IchthusWebApp', '0006_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
