# Generated by Django 4.1.3 on 2022-12-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IchthusWebApp', '0007_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='nergens', max_length=200),
            preserve_default=False,
        ),
    ]
